project:
  type: website
  output-dir: docs
  
website:
  title: "Miao Li, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: projects.qmd
        text: Work in Progress
      - href: blog/index.qmd
        text: blog
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://r4miao.github.io/MIDFIELD/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/) in [Rstudio](https://posit.co/download/rstudio-desktop/)"
    center: "&copy; Copyright 2024, Miao Li"

format:
  html:
    theme: minty
    toc: false

editor: source

