project:
  type: website
  output-dir: docs
  
website:
  title: "Miao Li, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/r4miao/MIDFIELD
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Miao Li"

format:
  html:
    theme: minty
    toc: true

editor: source

