---
title:  ""
---

1.  Li, Miao, Weidong Wang, Bei Liu, and Sarah Mustillo. (2024)."Combined nutrition and psychosocial stimulation intervention for child development in rural China: the role of parental resources" *Chinese Sociological Review*, 1-28. https://doi.org/10.1080/21620555.2024.2305787

2.  Li, Miao and Ye Luo. (2023). Physical Disability, Psychological Resilience and COVID-related Changes in Depressive Symptoms among U.S. Older Adults. *The Journals of Gerontology: Series B*, gbad025. https://doi.org/10.1093/geronb/gbad025

3.  Li, Miao and Ye Luo. (2023). Race-Ethnicity and Depressive Symptoms Among U.S. Older Adults in the COVID-19 Pandemic: Uncovering the Counterbalancing Mechanisms. Innovation in Aging. https://doi.org/10.1093/geroni/igad003

4.  Wang, Weidong*, and Miao Li*. (2023). Daily work stress and parent-to-child aggression: moderation of grandparent coresidence. Chinese Sociological Review, 1-20. https://doi.org/10.1080/21620555.2023.2165060 (\*Equal contribution)

5.  Li, Miao and Weidong Wang. (2021). Educational Disparities in COVID-19 Prevention in China: The Role of Contextual Danger, Perceived Risk, and Interventional Context. International journal of environmental research and public health, 18(7), 3383.

6.  Mustillo, Sarah. A., Li, Miao., Morton, Patricia., & Ferraro, Ken. F. (2021). Early Origins of Body Mass in Later Life: Examining Childhood Risks and Adult Pathways. Journal of Health and Social Behavior, 62(2), 152--169

7.  Mustillo, Sarah, Miao Li, and Weidong Wang. (2021). "Parent Work-to-Family Conflict and Child Psychological Well-being: Moderating Role of Grandparent Coresidence". Journal of Marriage and Family. 83: 27--39

8.  Li, Miao. (2020). "College Expectation in Adolescence and Nutritional Health in Early Adulthood: The hidden cost of social position." Social Science & Medicine. 265 (online first): 113482

9.  Li, Miao, and Sarah Mustillo. (2020). "Linking Maternal and Offspring Depression: A self-worth process explanation". Journal of Affective Disorders. 273(1): 113-121.

10. Mustillo, Sarah, Miao Li, and Ken Ferraro. (2019). "Evaluating the Cumulative Impact of Childhood Misfortune: A Structural Equation Modeling Approach." Sociological Methods & Research. 50(3), 1073--1109.

11. Li, Miao, Rong Fu, Hong Xue, and Youfa Wang. (2019). "Maternal Obesity and Children's Peer Victimization: The Intergenerational Impact of Weight-based Stigma." Journal of Health and Social Behavior. 60(1): 69-83.

12. Li, Miao, Sarah Mustillo, and James Anderson. (2018). "Childhood poverty dynamics and adulthood overweight/obesity: Unpacking the black box of childhood." Social Science Research. 76: 92-104.

13. Li, Miao, Sarah Mustillo, and Weidong Wang. (2018). "Perceived Discrimination, Screen Use, and BMI among Rural-to-Urban Migrant Children in China: Evidence from A Nutrition Transition Context." Journal of Immigrant and Minority Health.

14. Li, Miao, Fenggang Yang, Yun Lu. (2018). "Religious Plausibility of Chinese College Students: State, Science, and Social Network." Religions. 9(10):309

15. Li, Miao, Youfa Wang, Hong Xue, Jungwon Min. (2017). "Increased Obesity Risks for Being an Only Child in China: Findings from a nationally representative study of 19,487 children." Public Health. 153: 44--51.

16. Li, Miao, Hong Xue, Peng Jia, Yaling Zhao, Zhiyong Wang, Fei Xu and Youfa Wang. (2017). "Pocket Money, Eating Behaviors, and Weight Status among Chinese Children: The Childhood Obesity Study in China Mega-cities." Preventive Medicine. 100: 208-215.

17. Jia, Peng*, Miao Li*, Hong Xue, and Youfa Wang. (2017). "School Environment and Policies and Associations With Child Eating Behaviors and Weight Status in Urban China: The Childhood Obesity Study in China Mega-cities". International Journal of Obesity. 41: 813--819. (\*Equal contribution)

18. Min, Jungwon, Hong Xue, Vivian Wang, Miao Li, and Youfa Wang. (2017). "Are single children more likely to be overweight or obese than those with siblings? The influence of China's one-child policy on childhood obesity." Preventive Medicine. 103: 8-13.

19. Li, Miao, Hong Xue, Weidong Wang, and Youfa Wang. (2017). "Parental Expectations and Children's Screen-based and Academic-related Sedentary Behaviors in China: A Nationally Representative Study." American Journal of Preventive Medicine. 52(5): 680-689.

20. Wang, Youfa, Jungwon Min, Jacob Khuri, and Miao Li. (2017). "A Systematic Examination of the Association Between Parental and Child Obesity Across Countries." Advances in Nutrition. 8: 436-448.

21. Li, Miao, Hong Xue, Min Wen, Weidong Wang, and Youfa Wang. (2016). "Nutrition and Physical Activity Related School Environment/Policy Factors and Child Obesity in China: A Nationally Representative Study of 8,573 Students in 110 Middle Schools." Pediatric Obesity.

22. Olson, Dan, and Miao Li. (2015). "Does a Nation's Religious Composition Affect Generalized Trust? The Role of Religious Heterogeneity and the Percent Religious." Journal for the Scientific Study of Religion. 54(4):756--773.

23. Li, Miao. (2015). "Chronic Poverty Exposure of Grandparents and BMI Trajectories of Grandchildren: A Prospective Intergenerational Study." American Journal of Epidemiology. 181(3):163-170.

24. Li, Miao and Anderson, James G. (2015). "Pre-migration Trauma Exposure and Psychological Distress for Asian American Immigrants: Linking the Pre- and Post-Migration Contexts." Journal of Immigrant and Minority Health. 18(4), 728-739.

25. Li, Miao. (2015). "Pre-migration Trauma and Post-Migration Acculturative Stressors: Transnational Stress Proliferation." Social Indicators Research. 18(4):728-739.

26. Li, Miao. (2014). "Discrimination and Psychiatric Disorder among Asian American Immigrants: A National Analysis by Subgroups." Journal of Immigrant and Minority Health, 16(6): 1157-1166.

27. Tay, Louis, Miao Li, David Myers, and Ed. Diener. (2013). "Religiosity and Subjective Well-Being: An International Perspective." Pp. 163-76 in Religion and Spirituality Across Cultures, edited by Chu Kim-Prieto. New York: Springer.\

28. Yang, Guangbin, and Miao Li. (2009). "Western Political Theories and the Development of Political Theories in China", Journal of Chinese Political Science, 14: 275--297.
